# Default values for cats8
replicaCount: 1

image:
  repository: ghcr.io/albal/cats8
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# NGINX configuration
nginx:
  config:
    serverName: localhost
    # Health check endpoint
    healthCheck:
      enabled: true
      path: /health

# HTML content configuration
html:
  title: "Random Cat Service"
  refreshInterval: 60000  # milliseconds
  catApiUrl: "https://cataas.com/cat"
