apiVersion: v1
kind: Service
metadata:
  name: {{ include "cats8.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cats8.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "cats8.selectorLabels" . | nindent 4 }}
