apiVersion: v1
kind: Service
metadata:
  name: {{ include "cats8.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cats8.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cats8.selectorLabels" . | nindent 4 }}
