name: Publish Helm Chart

# Trigger on release published or manual workflow dispatch
on:
  release:
    types: [published]
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/helm-publish.yml'
  workflow_dispatch:

# Required permissions for GitHub Pages deployment
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.0'

      - name: Determine if release and extract version
        id: release_info
        run: |
          # Check if this is a release event
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
            # Extract version from tag name (format: 1.2.3, not v1.2.3)
            VERSION="${{ github.event.release.tag_name }}"
            # Remove 'v' prefix if present (though requirements say it won't have it)
            VERSION="${VERSION#v}"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Release version: $VERSION"
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
            echo "Not a release event - will build and test but not publish"
          fi

      - name: Update Chart version for release
        if: steps.release_info.outputs.is_release == 'true'
        run: |
          VERSION="${{ steps.release_info.outputs.version }}"
          echo "Updating Chart.yaml version to: $VERSION"
          sed -i "s/^version:.*/version: $VERSION/" charts/cats8/Chart.yaml
          echo "Updated Chart.yaml:"
          grep '^version:' charts/cats8/Chart.yaml

      - name: Lint Helm chart
        run: |
          helm lint charts/cats8

      - name: Create output directory
        if: steps.release_info.outputs.is_release == 'true'
        run: |
          mkdir -p .helmrepo

      - name: Checkout gh-pages branch
        if: steps.release_info.outputs.is_release == 'true'
        continue-on-error: true
        run: |
          # Try to fetch existing gh-pages branch
          git fetch origin gh-pages:gh-pages || echo "gh-pages branch does not exist yet"
          
          # If gh-pages exists, checkout and copy index.yaml
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout gh-pages
            if [ -f index.yaml ]; then
              cp index.yaml .helmrepo/index.yaml
              echo "Existing index.yaml found and copied"
            fi
            git checkout -
          else
            echo "No existing gh-pages branch, will create new one"
          fi

      - name: Package Helm chart
        if: steps.release_info.outputs.is_release == 'true'
        run: |
          # Package the chart
          helm package charts/cats8 -d .helmrepo
          
          # Get chart info
          CHART_VERSION=$(grep '^version:' charts/cats8/Chart.yaml | awk '{print $2}')
          CHART_NAME=$(grep '^name:' charts/cats8/Chart.yaml | awk '{print $2}')
          echo "Packaged ${CHART_NAME} version ${CHART_VERSION}"
          
          # Update or create index
          REPO_URL="https://$(echo $GITHUB_REPOSITORY | cut -d'/' -f1).github.io/$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)"
          echo "Repository URL: ${REPO_URL}"
          
          if [ -f .helmrepo/index.yaml ]; then
            echo "Merging with existing index.yaml"
            helm repo index .helmrepo --url "${REPO_URL}" --merge .helmrepo/index.yaml
          else
            echo "Creating new index.yaml"
            helm repo index .helmrepo --url "${REPO_URL}"
          fi

      - name: Deploy to GitHub Pages
        if: steps.release_info.outputs.is_release == 'true'
        run: |
          # Move .helmrepo to temp location before switching branches
          # This prevents it from being removed by git clean
          TEMP_HELM_DIR=$(mktemp -d)
          trap "rm -rf $TEMP_HELM_DIR" EXIT
          
          # Verify .helmrepo exists and has content before copying
          if [ ! -d .helmrepo ] || [ -z "$(ls -A .helmrepo 2>/dev/null)" ]; then
            echo "Error: .helmrepo directory not found or empty"
            exit 1
          fi
          
          cp -r .helmrepo/* "$TEMP_HELM_DIR/"
          echo "Copied .helmrepo contents to $TEMP_HELM_DIR"
          
          # Stash any local changes (like Chart.yaml version updates) before switching branches
          git stash --include-untracked || true
          
          # Create or switch to gh-pages branch
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout gh-pages
            # Remove old chart files but keep .git
            git rm -rf . || true
            git clean -fxd
          else
            # Create orphan gh-pages branch
            git checkout --orphan gh-pages
            git rm -rf . || true
          fi
          
          # Copy packaged charts and index from temp location to root
          if [ -d "$TEMP_HELM_DIR" ] && [ "$(ls -A $TEMP_HELM_DIR)" ]; then
            cp -r "$TEMP_HELM_DIR"/* .
            echo "Copied charts from temp location to gh-pages branch"
          else
            echo "Error: Temp helm directory not found or empty"
            exit 1
          fi
          
          # Create a simple index.html for the helm repo
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Cats8 Helm Repository</title>
            <style>
              body {
                font-family: Arial, sans-serif;
                max-width: 800px;
                margin: 50px auto;
                padding: 20px;
                background: #f5f5f5;
              }
              .container {
                background: white;
                padding: 30px;
                border-radius: 8px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
              }
              h1 { color: #333; }
              code {
                background: #f4f4f4;
                padding: 2px 6px;
                border-radius: 3px;
                font-family: monospace;
              }
              pre {
                background: #f4f4f4;
                padding: 15px;
                border-radius: 5px;
                overflow-x: auto;
              }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>🐱 Cats8 Helm Repository</h1>
              <p>This is a Helm chart repository for the Cats8 application.</p>
              
              <h2>Usage</h2>
              <p>Add this repository to Helm:</p>
              <pre><code>helm repo add cats8 https://albal.github.io/cats8
          helm repo update</code></pre>
              
              <h2>Install the Chart</h2>
              <pre><code>helm install my-cats cats8/cats8</code></pre>
              
              <h2>Available Charts</h2>
              <p>View the <a href="index.yaml">index.yaml</a> for available chart versions.</p>
              
              <h2>Documentation</h2>
              <p>Visit the <a href="https://github.com/albal/cats8">GitHub repository</a> for more information.</p>
            </div>
          </body>
          </html>
          EOF
          
          # Add and commit all files
          git add .
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Publish Helm chart - $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin gh-pages --force
            echo "Helm chart published to gh-pages"
          fi

      - name: Summary
        if: success()
        run: |
          if [ "${{ steps.release_info.outputs.is_release }}" = "true" ]; then
            echo "✅ Helm chart successfully published to GitHub Pages"
            echo "📦 Repository URL: https://$(echo $GITHUB_REPOSITORY | cut -d'/' -f1).github.io/$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)"
            echo "📌 Version: ${{ steps.release_info.outputs.version }}"
            echo ""
            echo "To use this chart:"
            echo "  helm repo add cats8 https://$(echo $GITHUB_REPOSITORY | cut -d'/' -f1).github.io/$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)"
            echo "  helm repo update"
            echo "  helm install my-cats cats8/cats8"
          else
            echo "✅ Helm chart linted and tested successfully"
            echo "📝 Chart was not published (not a release event)"
            echo ""
            echo "To publish this chart, create a release with a tag in format: 1.2.3"
          fi
